// describe('My First Test', () => {
//   it('Visit Page-Test', () => {
//     cy.visit('http://localhost:3000')
//     .url()
//     .should('include', '3000')
//   })
//   it('Next Page-Test', () => {
//     cy.visit('http://localhost:3000')
//     .get('.btn-15') 
//     .click()
//     .url()
//     .should('include', 'users/new')
//   })
//   it('Type Name-Test', () => {
//     cy.visit('http://localhost:3000')
//       .get('.btn-15') 
//       .click()
//       .get('.username')
//       .should('be.visible')
//       .type('Xouper')
//       .should('have.value', 'Xouper')
//   })
//   it('Password-Test', () => {
//     cy.visit('http://localhost:3000')
//     .get('.btn-15') 
//     .click()
//     .get('.username')
//     .type('Xouper')
//     .get('#password')
//     .should('be.visible')
//     .type('2281')
//     .should('have.value', '2281')
// })
// })
describe ('Full-Test', () => {
  it('Full-Test', () => {
    cy.visit('http://localhost:3000/users')
    cy.wait(1000)
    cy.visit('http://localhost:3000')
    .url()
    .should('include', '3000')
    cy.wait(1000)
    .get('.btn-15') 
    .click()
    .url()
    .should('include', 'users/new')
    cy.wait(1000)
    .get('.username')
    .should('be.visible')
    .type('Xouper')
    .should('have.value', 'Xouper')
    cy.wait(1000)
    .get('#password')
    .should('be.visible')
    .type('2281')
    .should('have.value', '2281')
    cy.wait(1000)
    .get('#submit')
    .should('be.visible')
    .click()
    .url()
    .should('include', 'users/')
    cy.visit('http://localhost:3000/test/tt.html')
    .url('include', 'test')
    cy.wait(1000)
    .get('.btn-14')
    .should('be.visible')
    .click()
    cy.wait(1000)
})
})